#!/usr/bin/env python3
"""
API Configuration Helper
Helps identify the correct API endpoint and format for your API key
"""

import requests

def test_openai_api(api_key):
    """Test if the API key works with OpenAI"""
    print("Testing OpenAI API...")
    
    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json'
    }
    
    # Simple test payload
    payload = {
        'model': 'gpt-3.5-turbo',
        'messages': [{'role': 'user', 'content': 'Hello'}],
        'max_tokens': 5
    }
    
    try:
        response = requests.post(
            'https://api.openai.com/v1/chat/completions',
            headers=headers,
            json=payload,
            timeout=30
        )
        
        if response.status_code == 200:
            print("✅ OpenAI API works!")
            return True
        else:
            print(f"❌ OpenAI API failed: {response.status_code} - {response.text}")
            return False
            
    except Exception as e:
        print(f"❌ OpenAI API error: {str(e)}")
        return False

def analyze_api_key_format(api_key):
    """Analyze API key format to suggest provider"""
    print(f"\n🔍 Analyzing API key format...")
    print(f"Key: {api_key[:8]}...{api_key[-4:]}")
    print(f"Length: {len(api_key)} characters")
    
    if api_key.startswith('sk-'):
        print("📋 Format suggests: OpenAI API")
        return "openai"
    elif len(api_key) == 32 and api_key.isalnum():
        print("📋 Format suggests: Azure OpenAI or other service")
        return "azure_or_other"
    else:
        print("📋 Format suggests: Unknown service - check your API provider documentation")
        return "unknown"

def suggest_configurations(api_key):
    """Suggest different configuration options"""
    
    print(f"\n💡 CONFIGURATION SUGGESTIONS:")
    print("="*50)
    
    # OpenAI Configuration
    print("1️⃣ OpenAI API:")
    print(f'   API_KEY = "{api_key}"')
    print('   API_ENDPOINT = "https://api.openai.com/v1/chat/completions"')
    print('   MODEL_NAME = "gpt-4" or "gpt-3.5-turbo"')
    
    # Azure OpenAI Configuration  
    print("\n2️⃣ Azure OpenAI:")
    print(f'   API_KEY = "{api_key}"')
    print('   API_ENDPOINT = "https://YOUR-RESOURCE.openai.azure.com/openai/deployments/YOUR-MODEL/chat/completions?api-version=2024-02-15-preview"')
    print('   MODEL_NAME = "gpt-4" (or your deployment name)')
    
    # Other services
    print("\n3️⃣ Other Compatible Services:")
    print("   Check your API provider's documentation for:")
    print("   - Correct endpoint URL")
    print("   - Authentication method")
    print("   - Available model names")
    
    # Common alternatives
    print("\n🔗 Common API Providers:")
    print("   - OpenAI: https://platform.openai.com/docs/api-reference")
    print("   - Azure OpenAI: https://learn.microsoft.com/en-us/azure/ai-services/openai/")
    print("   - Anthropic Claude: https://docs.anthropic.com/")
    print("   - Google AI: https://ai.google.dev/docs")
    print("   - Local/Self-hosted: Check your local server documentation")

def interactive_config():
    """Interactive configuration helper"""
    
    print("🛠️ INTERACTIVE API CONFIGURATION")
    print("="*50)
    
    api_key = input("Enter your API key: ").strip()
    if not api_key:
        print("❌ No API key provided")
        return
    
    provider = analyze_api_key_format(api_key)
    
    if provider == "openai":
        if test_openai_api(api_key):
            print("\n✅ OpenAI configuration confirmed!")
            create_working_config(api_key, "https://api.openai.com/v1/chat/completions", "gpt-4")
        else:
            print("\n❌ OpenAI test failed - key might be invalid or expired")
    
    else:
        print(f"\n⚠️ Non-OpenAI key detected")
        print("Please check with your API provider for the correct endpoint.")
        
        custom_endpoint = input("Enter your API endpoint URL (or press Enter to skip): ").strip()
        model_name = input("Enter your model name (or press Enter for 'gpt-4'): ").strip() or "gpt-4"
        
        if custom_endpoint:
            create_working_config(api_key, custom_endpoint, model_name)
        else:
            suggest_configurations(api_key)

def create_working_config(api_key, endpoint, model):
    """Create a working configuration file"""
    
    config_content = f'''# Room B Evaluator Configuration - AUTO GENERATED
# Generated by configuration helper

# API Configuration
API_KEY = "{api_key}"
API_ENDPOINT = "{endpoint}"
MODEL_NAME = "{model}"

# Evaluation Settings
EVALUATION_TEMPERATURE = 0.1  # Low temperature for consistent evaluations
MAX_TOKENS = 2000  # Maximum tokens for evaluation response

# Scoring Thresholds
APPROVAL_THRESHOLD = 75  # Composite score threshold for APPROVE (out of 90)
REVISION_THRESHOLD = 60  # Composite score threshold for REVISE (out of 90)

# Output Settings
DEFAULT_OUTPUT_DIR = "evaluation_results"
INCLUDE_FULL_RESPONSE = True
AUTO_SAVE_RESULTS = True
'''
    
    try:
        with open('config.py', 'w', encoding='utf-8') as f:
            f.write(config_content)
        
        print(f"\n✅ Configuration saved to config.py")
        print("You can now run test_evaluator.py to test the setup")
        
    except Exception as e:
        print(f"❌ Error saving config: {str(e)}")

def main():
    print("🔧 Room B Evaluator API Configuration Helper")
    print("="*50)
    
    # Try to read existing config
    try:
        from config import API_KEY, API_ENDPOINT, MODEL_NAME
        print(f"📁 Found existing config:")
        print(f"   API Key: {API_KEY[:8]}...{API_KEY[-4:]}")
        print(f"   Endpoint: {API_ENDPOINT}")
        print(f"   Model: {MODEL_NAME}")
        
        test_existing = input("\nTest existing configuration? (y/n): ").lower().startswith('y')
        if test_existing:
            provider = analyze_api_key_format(API_KEY)
            if provider == "openai":
                test_openai_api(API_KEY)
            suggest_configurations(API_KEY)
        
    except ImportError:
        print("📁 No existing config found")
    
    reconfigure = input("\nConfigure API settings? (y/n): ").lower().startswith('y')
    if reconfigure:
        interactive_config()
    else:
        print("\n💡 Manual configuration tips:")
        suggest_configurations("YOUR_API_KEY_HERE")

if __name__ == "__main__":
    main()